- Source/artifacts/IArtifacts.ts
- Source/events/EventStore.ts
The code assumed one of the overload signatures, while it is the last signature that decides what is actually available.
The exception that was thrown was 'event is not defined', which is true when looking at the transpiled output of the original code.
> Fixing a problem with commit() not internally using the correct argument when passing on internally

- Source/artifacts/Artifacts.ts
The consequence of this when used by the EventHandlerProcessor is that it never matched any types associated and all events became `[object Object]`.
> Fixing equality check for generation

- Source/sdk/Client.ts
- Source/sdk/index.ts
Client had an import to index which in turn exports Client. This can cause some real weird errors.
> avoid recursive imports for index

- README.md
Small Readme fix concerning misplaced 'C#' in the installation step.
- None
- Text change: 'C#' --> 'JS' at line 20 of README.md
- None
- None
- None
- None
> C# --> JS fix when describing installation script.

- .github/workflows/workflow.yml
Add the embeddings prerelease branch to GitHub workflow to release embeddings as we go.
> Add embeddings as a prerelease branch

- Source/aggregates/AggregateRoot.ts
- Source/aggregates/for_AggregateRoot/when_applying_public_events.ts
- Source/aggregates/for_Dummy/when_nothing.ts
Fixes `applyPublic()` to actually be public. It was giving false for the `isPublic` parameter for the committing of the event.
- Fixes `applyPublic()` to actually commit public events.
> Setting public to true when applying public events

- Source/common/IContainer.ts
- Source/common/package.json
- Source/events.handling/Builder/EventHandlerClassBuilder.ts
Adds the current `ExecutionContext` as an argument to `IContainer.get(...)` and sends it along from the `EventContext` when instantiating event handler classes.
- Added `executionContext: ExecutionContext` as an argument in `IContainer.get(...)`.
> Pass along ExecutionContext to Container for DI

- Samples/Tutorials/Embeddings/index.ts
- Source/embeddings/Embedding.ts
- Source/embeddings/IEmbedding.ts
Renames the call to delete an embedding from`embeddings.delete()` to `embeddings.remove()`, so that it's consistent with the `@remove()` decorator and inline builder naming.
Originally the decorators were also supposed to be called `@delete()`, but as `delete` is a reserved keyword in JS, we changed them to `@remove()`, but didn't think of changing the deletion call too to match. Internally the processor and contracts still call it `delete`, this change only affects the outside facing API.
- Change the `embeddings.delete()` call to `embeddings.remove()`.
> Rename `embeddings.delete()` to `embeddings.remove()`

- Source/sdk/package.json
Adding "sdk.embeddings" to the "sdk" package.json.
- Adding sdk.embeddings to sdk, making the npm package include the new embeddings work
> Adding sdk.embeddings to the sdk

- Source/embeddings/Builder/EmbeddingClassBuilder.ts
- Source/embeddings/Internal/EmbeddingDeleteMethodFailed.ts
- Source/embeddings/Internal/EmbeddingUpdateMethodFailed.ts
- Source/events.handling/Builder/CouldNotCreateInstanceOfEventHandler.ts
- Source/events.handling/Builder/EventHandlerClassBuilder.ts
- Source/events.processing/Internal/EventProcessor.ts
- Source/projections/Builder/ProjectionClassBuilder.ts
- Source/protobuf/for_eventTypes/when_converting_from_protobuf_with_missing_id.ts
- Source/protobuf/for_failures/when_converting_from_protobuf_with_missing_id.ts
Fixes a bug where `async` Event Handler methods were not properly awaited (and thus also exceptions ignored) if they did any async work. In the process, also found a bug related to _delete results_ returned from async Projection and Embedding methods, that would not be handled correctly.
- Return the `Promise` from Event Handler methods in the EventHandlerClassBuilder to handle async methods properly.
- Await results from Projection/Embedding `on()` methods, so that async _delete results_ are handled properly.
> Fix eventhandler async methods

- Source/artifacts/package.json
- Source/embeddings/Internal/EmbeddingProcessor.ts
- Source/embeddings/package.json
- Source/eventHorizon/EventHorizons.ts
- Source/eventHorizon/SubscriptionBuilderForProducerStream.ts
- Source/eventHorizon/package.json
- Source/events.filtering/Internal/FilterEventProcessor.ts
- Source/events.filtering/Internal/PartitionedEventFilterProcessor.ts
- Source/events.filtering/Internal/PublicEventFilterProcessor.ts
- Source/events.filtering/PartitionedFilterResult.ts
- Source/events.filtering/package.json
- Source/events.handling/Internal/EventHandlerProcessor.ts
- Source/events.handling/package.json
- Source/events.processing/package.json
- Source/events/EventConverters.ts
- Source/events/EventSourceId.ts
- Source/events/EventStore.ts
- Source/events/PartitionId.ts
- Source/events/UncommittedAggregateEvents.ts
- Source/events/package.json
- Source/projections/Internal/ProjectionProcessor.ts
- Source/projections/package.json
- Source/protobuf/package.json
- Source/sdk/package.json
- Source/services/package.json
Update to new contracts that changes partition and event source id to be a string instead of a guid. Fix all build errors that
> Event source concept

- .github/workflows/ms-teams-release.yml
Uses the correct release event type
- Use the correct release event type, 'published'
> Fix-on-event

- Source/resilience/Cancellation.ts
- Source/resilience/CancellationSource.ts
- Source/resilience/for_Cancellation/when_checking_if_instanceof_cancellation/a_new_cancellation.ts
- Source/resilience/for_Cancellation/when_checking_if_instanceof_cancellation/and_is_default_cancellation.ts
- Source/resilience/for_CancellationSource/when_checking_if_instanceof_cancellation/from_a_new_source.ts
Fixes an issue with the implementation of `Cancellation` where `instanceof` did not work.
> Fix cancellation instanceof

- .gitignore
- Assets/copy-readme.js
- Source/aggregates/package.json
- Source/artifacts/package.json
- Source/common/package.json
- Source/embeddings/package.json
- Source/eventHorizon/package.json
- Source/events.filtering/package.json
- Source/events.handling/package.json
- Source/events.processing/package.json
- Source/events/package.json
- Source/execution/package.json
- Source/projections/package.json
- Source/protobuf/package.json
- Source/resilience/package.json
- Source/resources/package.json
- Source/sdk/package.json
- Source/services/package.json
- Source/tenancy/package.json
- package.json
Introducing a new build script that copies over the README.md file to the root of each project to be packaged and published to npm.
- Build script that copies the README.md file to the root of each package before building
> Add readme to packages

- Assets/PACKAGE-README.md
- Assets/copy-readme.js
Use a custom README file for publishing to npmjs. To keep it consistent with the C# SDK - and we don't need all that building stuff for NPM.
- The published README file.
> Custom nom package README

- .github/workflows/workflow.yml
- Source/sdk/VersionInfo.ts
Adds VersionInfo to be set during build.
- VersionInfo class in `@dolittle/sdk`
- Update Version Info step in GitHub workflow
> Add VersionInfo class and workflow step.

- Source/sdk/VersionInfo.ts
These numbers should not be changed. They were committed by the `release-typescript-lib-action`, but they should not. The action has also been patched to fix this behaviour: https://github.com/dolittle/release-typescript-lib-action/pull/24
- Magic numbers in `VersionInfo.ts`
> Fix magic numbers in VersionInfo

- Source/dependencyInversion/Internal/Extensions/DelegatingResolver.ts
- Source/dependencyInversion/Internal/Implementations/TypeDIServiceProvider.ts
- Source/dependencyInversion/Internal/Implementations/_exports.ts
- Source/dependencyInversion/KnownServiceProviders.ts
- Source/dependencyInversion/Types/TSyringeContainer.ts
- Source/dependencyInversion/Types/TypeDIContainer.ts
- Source/dependencyInversion/Types/_exports.ts
- Source/dependencyInversion/createRootServiceProvider.ts
- Source/dependencyInversion/package.json
Fixes a bug where optional parameters to TSyringe methods caused the isTSyringeContainer to fail. Also adds support for TypeDI as external service provider.
- Support for TypeDI service provider.
- Bug where TSyringe containers where not properly identified.
> Fix TSyringe bugs and add support for TypeDI

- Source/dependencyInversion/Types/TypeDIContainer.ts
Allows passing in the global TypeDI container as an external service provider.
- Changed type definitions so you can pass inn the global TypeDI `Container` instance.
> Allow using the global TypeDI container

- Source/embeddings/Internal/EmbeddingProcessor.ts
- Source/events.filtering/Internal/FilterEventProcessor.ts
- Source/events.handling/Internal/EventHandlerProcessor.ts
- Source/events.processing/Internal/EventProcessor.ts
- Source/events/EventContext.ts
- Source/projections/Internal/ProjectionProcessor.ts
- Source/services/ClientProcessor.ts
- Source/services/IReverseCallClient.ts
Changed `EventContext` to contain both the current and the committed `ExecutionContext`, and fixed the event processors to include the committed event execution context.
- `EventContext` now has `committedExecutionContex`+`currentExecutionContext` instead of `executionContext`, and is in line with .NET SDK.
- Committed execution context not passed along by event processors.
> Fix processing execution context

- Samples/Tutorials/EventHorizon/Consumer/index.ts
- Samples/Tutorials/EventHorizon/Producer/index.ts
- Samples/Tutorials/Projections/index.ts
- Source/embeddings/Builders/EmbeddingsBuilder.ts
- Source/embeddings/Builders/IEmbeddingsBuilder.ts
- Source/events.filtering/EventFiltersBuilder.ts
- Source/events.filtering/IEventFiltersBuilder.ts
- Source/events.filtering/PrivateEventFilterBuilderCallback.ts
- Source/events.filtering/PublicEventFilterBuilderCallback.ts
- Source/events.filtering/_exports.ts
- Source/events.handling/Builders/EventHandlerBuilderCallback.ts
- Source/events.handling/Builders/EventHandlersBuilder.ts
- Source/events.handling/Builders/IEventHandlersBuilder.ts
- Source/events.handling/Builders/_exports.ts
- Source/events.handling/index.ts
- Source/projections/Builders/IProjectionsBuilder.ts
- Source/projections/Builders/ProjectionsBuilder.ts
- Source/sdk/Builders/SetupBuilder.ts
Make builders APIs all the same. Renamed all to be `register/create`, and for all to return the individual builders instead of accepting a callback to configure them.
- Builders methods are now called just `create(id)` or `register(type)` for all kinds.
- `create(id)` methods return the individual kind builder instead of accepting a callback (some already did this).
> Fix builders api

- Source/aggregates/Builders/AggregateRootsModelBuilder.ts
- Source/sdk/Builders/SetupBuilder.ts
Bind the `IAggregateOf<...>` into the DI container for the registered aggregate root types. Unfortunately the generics disappear when compiled to JavaScript, so the bindings are just with string identifiers - so you need to do something like `services.get('IAggregateOf<Kitchen>') as IAggregateOf<Kitchen>`.
> Bind IAggregateOg<> in the ServiceProvider

- Source/aggregates/package.json
- Source/artifacts/package.json
- Source/common/package.json
- Source/dependencyInversion/package.json
- Source/embeddings/package.json
- Source/eventHorizon/package.json
- Source/events.filtering/package.json
- Source/events.handling/package.json
- Source/events.processing/package.json
- Source/events/package.json
- Source/execution/package.json
- Source/extensions.express/package.json
- Source/projections/Store/ProjectionStore.ts
- Source/projections/Store/ReceivedDuplicateProjectionKeys.ts
- Source/projections/Store/_exports.ts
- Source/projections/Store/for_ProjectionStore/given.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_ids/and_it_returns_a_failure.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_ids/and_it_returns_multiple_batches.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_ids/and_it_returns_the_same_key_multple_times.ts
- Source/projections/index.ts
- Source/projections/package.json
- Source/protobuf/package.json
- Source/resources/package.json
- Source/sdk/package.json
- Source/services/GrpcMethods.ts
- Source/services/ReactiveGrpc.ts
- Source/services/package.json
- Source/tenancy/package.json
Uses the new batch streaming method to get all Projection states from the Runtime. This fixes an issue where a large amount of Projection states caused the gRPC client in the SDK to throw an exception because the response message was too big. Also fixed some gRPC method internals that we haven't used before (server streaming calls), and fixed the references to JavaScript.Fundamentals pre-release packages.
- The `IProjectionStore.getAll` method now uses the new gRPC method that streams results back in batches to fix the issue of too large gRPC messages when a large amount of projection read models have been created.
> Projections GetAll batching

- Samples/ExpressJS/DishCounter.ts
- Samples/ExpressJS/index.ts
- Samples/Tutorials/Projections/DishCounter.ts
- Samples/Tutorials/Projections/index.ts
- Source/projections/Store/IProjectionStore.ts
- Source/projections/Store/ProjectionStore.ts
- Source/projections/Store/WrongKeyReceivedFromRuntime.ts
- Source/projections/Store/for_ProjectionStore/given.ts
- Source/projections/Store/for_ProjectionStore/given/a_projection_type.ts
- Source/projections/Store/for_ProjectionStore/when_getting/by_ids/and_it_returns_a_failure.ts
- Source/projections/Store/for_ProjectionStore/when_getting/by_ids/and_it_returns_the_wrong_key.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_ids/and_it_returns_multiple_batches.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_type/and_it_returns_a_failure.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_type/and_it_returns_multiple_batches.ts
- Source/projections/Store/for_ProjectionStore/when_getting_all/by_type/and_it_returns_the_same_key_multple_times.ts
Simplifies the `IProjectionStore` apis by removing the `CurrentState<>` wrapper around the returned types from `get(...)` and `getAll(...)` methods, and returns an array instead of a `Map` when getting multiple read models. And introduces a new `getState(...)` method that has the wrapped types for when it is interesting.
- `IProjectionStore.getState(...)` method that keeps the syntax of the previous `.get(...)` method.
- `IProjectionStore.get(...)` returns the specified type or `any` instead of wrapping with `CurrentState<>`
- `IProjectionStore.getAll(...)` returns an array of the specified type or `any` instead of a `Map` of keys to `CurrentState<>`.
> Simplify Projection Store API

- Source/resources/MongoDB/DbExtensions.ts
- Source/resources/MongoDB/_exports.ts
- Source/resources/package.json
- Source/resources/tsconfig.json
Extends the `Db.collection` method with an overload to more easily get the collection for a Projection read model type.
> Extend MongoDB Db.collection method

- Samples/MongoDBProjections/.eslintrc.js
- Samples/MongoDBProjections/DishCounter.ts
- Samples/MongoDBProjections/DishPrepared.ts
- Samples/MongoDBProjections/index.ts
- Samples/MongoDBProjections/package.json
- Samples/MongoDBProjections/tsconfig.json
- Samples/Tutorials/Projections/Chef.ts
- Samples/Tutorials/Projections/DishCounter.ts
- Samples/Tutorials/Projections/index.ts
- Source/artifacts/package.json
- Source/embeddings/package.json
- Source/eventHorizon/package.json
- Source/events.filtering/package.json
- Source/events.handling/package.json
- Source/events.processing/package.json
- Source/events/package.json
- Source/projections/package.json
- Source/protobuf/package.json
- Source/resources/package.json
- Source/sdk/package.json
- Source/services/package.json
- Source/tenancy/package.json
- package.json
Revert Tutorials/Projections, and add new MongoDBProjections sample. Upgrade to released contracts, and checked that it works with the released Runtime.
> Fix samples and upgrade to released contracts

- Source/artifacts/package.json
- Source/embeddings/package.json
- Source/eventHorizon/package.json
- Source/events.filtering/package.json
- Source/events.handling/package.json
- Source/events.processing/package.json
- Source/events/package.json
- Source/projections/Builders/KeySelectorBuilder.ts
- Source/projections/EventOccurredKeySelector.ts
- Source/projections/Internal/ProjectionProcessor.ts
- Source/projections/KeySelector.ts
- Source/projections/OccurredFormat.ts
- Source/projections/StaticKeySelector.ts
- Source/projections/_exports.ts
- Source/projections/package.json
- Source/protobuf/package.json
- Source/resources/package.json
- Source/sdk/package.json
- Source/services/package.json
- Source/tenancy/package.json
Adds two new event key selectors to projections, `StaticKey` and `KeyFromEventOccurred`
- `staticKey` event key selector attribute for projection On-methods that sets a constant, static, key as the key of the read model
- `keyFromEventOccurred` event key selector for projection On-methods that uses the event occurred metadata as the key for the projection read models formatted as the string given to the attribute. We currently support these formats:
- yyyy-MM-dd
- yyyy-MM
- yyyy
- HH:mm:ss
- hh:mm:ss
- HH:mm
- hh:mm
- HH
- hh
- yyyy-MM-dd HH:mm:ss
- And the above in different orderings
> Implement key selectors

- Source/events.processing/Internal/EventProcessor.ts
Fixes a bug that resulted in wrong retry timings when processing of events failed.
- The event processing retry time should now increment in the correct interval
> Fix retry time for events processing
